@extends('layouts.admin')
@section('title', 'Shipment details')
@section('content')
    <div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow mb-4 text-olive-600">Shipment #{{ $shipment->id }} / {{ $shipment->transport_type->label() }}</p><h1 class="display-title text-4xl sm:text-5xl">{{ $shipment->departure_location }} <span class="text-olive-500">→</span> {{ $shipment->destination }}</h1><p class="mt-4 text-sm text-stone-500">{{ $shipment->status->label() }}</p></div><div class="flex flex-wrap gap-3"><a class="btn-secondary" href="{{ route(request()->routeIs('admin.*') ? 'admin.shipments.index' : 'distributor.shipments.index') }}">Back to shipments</a>@unless(request()->routeIs('admin.*'))<a class="btn-primary" href="{{ route('distributor.shipments.edit', $shipment) }}">Edit shipment</a>@endunless</div></div>
    <div class="grid gap-6 lg:grid-cols-2">
        <x-card><h2 class="font-display text-2xl">Shipment record</h2><dl class="mt-6 grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-stone-500">Product</dt><dd class="mt-2 font-semibold">{{ $shipment->oilProduct->name }}</dd></div><div><dt class="text-stone-500">Brand</dt><dd class="mt-2 font-semibold">{{ $shipment->oilProduct->brand }}</dd></div><div><dt class="text-stone-500">Status</dt><dd class="mt-2"><span class="role-badge">{{ $shipment->status->label() }}</span></dd></div><div><dt class="text-stone-500">Transport</dt><dd class="mt-2 font-semibold">{{ $shipment->transport_type->label() }}</dd></div><div><dt class="text-stone-500">Distance</dt><dd class="mt-2 font-semibold">{{ $shipment->distance_km }} km</dd></div><div><dt class="text-stone-500">Recorded CO₂</dt><dd class="mt-2 font-semibold">{{ $shipment->co2_estimate === null ? 'Not available' : $shipment->co2_estimate.' kg' }}</dd></div></dl></x-card>
        <x-card><h2 class="font-display text-2xl">Journey and distributor</h2><dl class="mt-6 grid gap-5 text-sm"><div><dt class="text-stone-500">Distributor</dt><dd class="mt-2 font-semibold">{{ $shipment->distributorProfile->company_name }}</dd></div><div><dt class="text-stone-500">Departure date</dt><dd class="mt-2 font-semibold">{{ $shipment->departure_date->format('d/m/Y') }}</dd></div><div><dt class="text-stone-500">Arrival date</dt><dd class="mt-2 font-semibold">{{ $shipment->arrival_date?->format('d/m/Y') ?? 'Not recorded' }}</dd></div></dl></x-card>
    </div>
@endsection
