<x-card>
    <p class="eyebrow mb-3 text-olive-600">Sustainability assistant</p>
    <h2 class="font-display text-2xl">A second perspective.</h2>
    <p class="mt-3 text-sm leading-6 text-stone-500">Ask AI for practical suggestions using region, area, variety and cultivation practices. Contact details, exact coordinates and free-text notes are not sent.</p>
    <form method="POST" action="{{ route($admin ? 'admin.farms.advice' : 'producer.farms.advice', $farm->id) }}" class="mt-5" x-data="{ loading: false }" @submit="loading = true">
        @csrf
        <button class="btn-secondary" type="submit" :disabled="loading"><span x-show="!loading">Generate suggestions</span><span x-show="loading" x-cloak role="status">Preparing suggestions…</span></button>
    </form>
    <p class="mt-4 text-xs leading-5 text-stone-500">Advisory only. Review suggestions with a local agronomist. AI never changes your records or certifies your farm.</p>
    @isset($assistantResult)
        <div class="mt-6 border-t border-stone-100 pt-6" role="status">
            @if($assistantResult['available'])
                <p class="text-sm leading-6">{{ $assistantResult['advice']['summary'] }}</p>
                @foreach(['suggestions' => 'Suggestions to consider', 'flags' => 'Information to review'] as $key => $label)
                    <h3 class="mb-3 mt-5 text-sm font-semibold">{{ $label }}</h3>
                    @if(count($assistantResult['advice'][$key]))<ul class="list-disc space-y-2 pl-5 text-sm leading-6 text-stone-600">@foreach($assistantResult['advice'][$key] as $item)<li>{{ $item }}</li>@endforeach</ul>@else<p class="text-sm text-stone-500">No items suggested.</p>@endif
                @endforeach
                <p class="mt-5 rounded-xl bg-olive-50 p-4 text-xs leading-6">{{ $assistantResult['advice']['limitations'] }}</p>
                <p class="mt-3 text-xs text-stone-500">Generated by {{ $assistantResult['provider'] }} · {{ $assistantResult['model'] }}</p>
            @else<p class="text-sm leading-6 text-stone-500">{{ $assistantResult['message'] }}</p>@endif
        </div>
    @endisset
</x-card>
